name: Build Image
description: "Build a docker image and stores it as an artifact"
inputs:
  projectName:
    description: Project name
    required: true

runs:
  using: composite
  steps:
    - name: Install Node & Dependencies
      uses: cpdevtools/common-github-workflows/.github/actions/node-setup-pnpm@main
      with:
        nodeVersion: 24.21.0
        pnpmVersion: 10.34.5

    - name: Build
      uses: cpdevtools/common-github-workflows/.github/actions/pnpm-run-recursive@main
      with:
        script: actions-build
        projectFilter: ${{ inputs.projectName }}

    - name: Run Tests
      uses: cpdevtools/common-github-workflows/.github/actions/pnpm-run-recursive@main
      with:
        script: actions-test
        projectFilter: ${{ inputs.projectName }}
